### ISSUE TITLE
ros and libtorch compile

### ISSUE THREAD

**Issue by maxwellfrom** [ActiveIntelligentSystemsLab/pytorch_enet_ros#1]
I met the problem that libtorch is conflict with ros when I compile my code, Have you encountered the same problem?

**Comment by ShigemichiMatsuzaki** [comment]
Hi, @maxwellfrom. Thanks for your interest in our software.

I've created a [Docker environment](https://github.com/ActiveIntelligentSystemsLab/pytorch-enet-docker) for PyTorch and ROS, and this package has only checked on the virtual environment.
You should therefore try running the program on the docker container.

The problem regarding to your another issue https://github.com/ActiveIntelligentSystemsLab/pytorch_enet_ros/issues/2 can also be solved, since the message package is also included in the Docker.

Please be reminded of several things.
- Although those repositories are public, they're primarily meant for my personal use, and are not well-maintained. (because of my poor skills and knowledge and devotion)
- As such, some of the codes are not general enough to be used for your purpose without modification. I hope the codes are still useful for you!
- There will be more problems in the future. Please report if you encountered another problem.
